// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Guide → Comparisons*
 */
export interface GuideDocumentDataComparisonsItem {
  /**
   * Rank1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Rank
   * - **API ID Path**: guide.comparisons[].rank1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rank1: prismic.KeyTextField;

  /**
   * Rank2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].rank2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rank2: prismic.KeyTextField;

  /**
   * Rank3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].rank3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rank3: prismic.KeyTextField;

  /**
   * Image1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * Image2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;

  /**
   * Title1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].title1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].title2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title2: prismic.KeyTextField;

  /**
   * Title3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].title3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title3: prismic.KeyTextField;

  /**
   * Name1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].name1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  name1: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Name2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].name2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  name2: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Name3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].name3
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  name3: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Paragraph1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].paragraph1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph1: prismic.KeyTextField;

  /**
   * Paragraph2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].paragraph2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph2: prismic.KeyTextField;

  /**
   * Paragraph3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].paragraph3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph3: prismic.KeyTextField;

  /**
   * Link1 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].link1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link1: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Link2 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].link2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link2: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Link3 field in *Guide → Comparisons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[].link3
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link3: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

type GuideDocumentDataSlicesSlice = never;

/**
 * Content for Guide documents
 */
interface GuideDocumentData {
  /**
   * Image field in *Guide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Author field in *Guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Date field in *Guide*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Guide field in *Guide*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.guide
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  guide: prismic.RichTextField;

  /**
   * Comparisons field in *Guide*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.comparisons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  comparisons: prismic.GroupField<Simplify<GuideDocumentDataComparisonsItem>>;

  /**
   * EndGuide field in *Guide*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.endguide
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  endguide: prismic.RichTextField;

  /**
   * Links field in *Guide*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *Guide*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<GuideDocumentDataSlicesSlice> /**
   * Meta Title field in *Guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: guide.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: guide.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Guide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Guide document from Prismic
 *
 * - **API ID**: `guide`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GuideDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<GuideDocumentData>, "guide", Lang>;

/**
 * Content for MarketingBanner documents
 */
interface MarketingbannerDocumentData {
  /**
   * Image field in *MarketingBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marketingbanner.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *MarketingBanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marketingbanner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Short Paragraph field in *MarketingBanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marketingbanner.short_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_paragraph: prismic.KeyTextField;

  /**
   * Link field in *MarketingBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: marketingbanner.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Offer field in *MarketingBanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marketingbanner.offer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offer: prismic.KeyTextField;
}

/**
 * MarketingBanner document from Prismic
 *
 * - **API ID**: `marketingbanner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MarketingbannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MarketingbannerDocumentData>,
    "marketingbanner",
    Lang
  >;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * link field in *Product*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Category field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Platform field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Platform
   * - **API ID Path**: product.platform
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * Discount field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Percentage discount
   * - **API ID Path**: product.discount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  discount: prismic.NumberField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

export type AllDocumentTypes =
  | GuideDocument
  | MarketingbannerDocument
  | ProductDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GuideDocument,
      GuideDocumentData,
      GuideDocumentDataComparisonsItem,
      GuideDocumentDataSlicesSlice,
      MarketingbannerDocument,
      MarketingbannerDocumentData,
      ProductDocument,
      ProductDocumentData,
      AllDocumentTypes,
    };
  }
}
