const products = [
    {
        id: "prod001",
        slug: "robot-vacuum-cleaner",
        name: "Robot Vacuum Cleaner",
        category: "Home Appliances",
        price: "299.99",
        oldPrice: "349.99",
        imageUrl: "https://images.unsplash.com/photo-1653990480360-31a12ce9723e?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.5,
        reviewCount: 150,
        onPromotion: true,
        shortDescription: "Efficient robot vacuum for automated home cleaning."
    },
    {
        id: "prod002",
        slug: "dashboard-camera",
        name: "Dashboard Camera",
        category: "Automotive Electronics",
        price: "79.99",
        imageUrl: "https://images.unsplash.com/photo-1716738547734-fb7cb39c5b2e?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.2,
        reviewCount: 80,
        onPromotion: false,
        shortDescription: "Reliable HD dashboard camera for your vehicle's security."
    },
    {
        id: "prod003",
        slug: "smart-home-thermostat",
        name: "Smart Home Thermostat",
        category: "Smart Home",
        price: "129.99",
        imageUrl: "https://plus.unsplash.com/premium_photo-1729436833449-225649403fc0?q=80&w=1934&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.7,
        reviewCount: 200,
        onPromotion: false,
        shortDescription: "Intelligent thermostat for optimal home climate control and energy savings."
    },
    {
        id: "prod004",
        slug: "ultrawide-qhd-monitor",
        name: "UltraWide QHD Monitor",
        category: "Monitors",
        price: "499.00",
        oldPrice: "599.00",
        imageUrl: "https://images.unsplash.com/photo-1701318134822-fcc7630206ed?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.8,
        reviewCount: 300,
        onPromotion: true,
        shortDescription: "Immersive ultra-wide QHD monitor for productivity and gaming."
    },
    {
        id: "prod005",
        slug: "hepa-air-purifier",
        name: "HEPA Air Purifier",
        category: "Home Appliances",
        price: "149.99",
        imageUrl: "https://images.unsplash.com/photo-1661767013569-da7dce8ea409?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.6,
        reviewCount: 250,
        onPromotion: false,
        shortDescription: "High-efficiency HEPA air purifier for cleaner indoor air quality."
    },
    {
        id: "prod006",
        slug: "programmable-coffee-maker",
        name: "Programmable Coffee Maker",
        category: "Kitchen Appliances",
        price: "89.99",
        oldPrice: "109.99",
        imageUrl: "https://somethingsbrewing.in/cdn/shop/files/PRO_2_black_hero_grey_mottled_copped_square_woo.jpg?v=1732604384&width=1946",
        amazonLink: "#",
        rating: 4.4,
        reviewCount: 180,
        onPromotion: true,
        shortDescription: "Advanced programmable coffee maker for the perfect brew every time."
    },
    {
        id: "prod007",
        slug: "premium-espresso-machine",
        name: "Premium Espresso Machine",
        category: "Kitchen Appliances",
        price: "199.00",
        imageUrl: "https://images.pexels.com/photos/362216/pexels-photo-362216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        amazonLink: "#",
        rating: 4.7,
        reviewCount: 220,
        onPromotion: false,
        shortDescription: "Classic espresso machine for authentic, barista-quality coffee at home."
    },
    {
        id: "prod008",
        slug: "high-performance-gaming-laptop",
        name: "High-Performance Gaming Laptop",
        category: "Laptops",
        price: "1299.00",
        oldPrice: "1499.00",
        imageUrl: "https://images.unsplash.com/photo-1640955014216-75201056c829?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.9,
        reviewCount: 400,
        onPromotion: true,
        shortDescription: "Top-tier gaming laptop with powerful specs for an immersive experience."
    },
    {
        id: "prod009",
        slug: "mechanical-gaming-keyboard",
        name: "Mechanical Gaming Keyboard",
        category: "Computer Accessories",
        price: "99.99",
        imageUrl: "https://images.unsplash.com/photo-1722666729526-1e801fe4eedb?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        amazonLink: "#",
        rating: 4.5,
        reviewCount: 160,
        onPromotion: false,
        shortDescription: "RGB mechanical keyboard with responsive keys for gaming and typing."
    },
    {
        id: "prod010",
        slug: "compact-espresso-maker",
        name: "Compact Espresso Maker",
        category: "Kitchen Appliances",
        price: "79.99",
        imageUrl: "https://images.pexels.com/photos/362216/pexels-photo-362216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        amazonLink: "#",
        rating: 4.3,
        reviewCount: 120,
        onPromotion: true,
        shortDescription: "Space-saving and efficient espresso maker for quick coffee fixes."
    }
]

export default products;