const products = [
    {
        id: "prod001",
        slug: "robot-vacuum-cleaner",
        name: "Robot Vacuum Cleaner",
        category: "Home Appliances",
        price: "299.99",
        oldPrice: "349.99",
        imageUrl: "https://unsplash.com/photos/a-black-robot-vacuum-on-a-wooden-floor-uhJgh4FHi6I",
        amazonLink: "#",
        rating: 4.5,
        reviewCount: 150,
        onPromotion: true,
        shortDescription: "Efficient robot vacuum for automated home cleaning."
    },
    {
        id: "prod002",
        slug: "dashboard-camera",
        name: "Dashboard Camera",
        category: "Automotive Electronics",
        price: "79.99",
        imageUrl: "https://unsplash.com/photos/a-car-dashboard-with-a-dash-camera-attached-to-it-dV4iz3ZS_vg",
        amazonLink: "#",
        rating: 4.2,
        reviewCount: 80,
        onPromotion: false,
        shortDescription: "Reliable HD dashboard camera for your vehicle's security."
    },
    {
        id: "prod003",
        slug: "smart-home-thermostat",
        name: "Smart Home Thermostat",
        category: "Smart Home",
        price: "129.99",
        imageUrl: "https://unsplash.com/photos/a-room-with-a-plant-and-a-thermostaer-on-the-wall-LUFaSAGhk1c",
        amazonLink: "#",
        rating: 4.7,
        reviewCount: 200,
        onPromotion: false,
        shortDescription: "Intelligent thermostat for optimal home climate control and energy savings."
    },
    {
        id: "prod004",
        slug: "ultrawide-qhd-monitor",
        name: "UltraWide QHD Monitor",
        category: "Monitors",
        price: "499.00",
        oldPrice: "599.00",
        imageUrl: "https://unsplash.com/photos/a-desk-with-a-monitor-keyboard-and-a-remote-control-16n_n_yevwQ",
        amazonLink: "#",
        rating: 4.8,
        reviewCount: 300,
        onPromotion: true,
        shortDescription: "Immersive ultra-wide QHD monitor for productivity and gaming."
    },
    {
        id: "prod005",
        slug: "hepa-air-purifier",
        name: "HEPA Air Purifier",
        category: "Home Appliances",
        price: "149.99",
        imageUrl: "https://unsplash.com/photos/a-white-rectangular-object-with-a-blue-logo-on-it-4j3kYZfR4m8",
        amazonLink: "#",
        rating: 4.6,
        reviewCount: 250,
        onPromotion: false,
        shortDescription: "High-efficiency HEPA air purifier for cleaner indoor air quality."
    },
    {
        id: "prod006",
        slug: "programmable-coffee-maker",
        name: "Programmable Coffee Maker",
        category: "Kitchen Appliances",
        price: "89.99",
        oldPrice: "109.99",
        imageUrl: "https://somethingsbrewing.in/cdn/shop/files/PRO_2_black_hero_grey_mottled_copped_square_woo.jpg?v=1732604384&width=1946",
        amazonLink: "#",
        rating: 4.4,
        reviewCount: 180,
        onPromotion: true,
        shortDescription: "Advanced programmable coffee maker for the perfect brew every time."
    },
    {
        id: "prod007",
        slug: "premium-espresso-machine",
        name: "Premium Espresso Machine",
        category: "Kitchen Appliances",
        price: "199.00",
        imageUrl: "https://images.pexels.com/photos/362216/pexels-photo-362216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        amazonLink: "#",
        rating: 4.7,
        reviewCount: 220,
        onPromotion: false,
        shortDescription: "Classic espresso machine for authentic, barista-quality coffee at home."
    },
    {
        id: "prod008",
        slug: "high-performance-gaming-laptop",
        name: "High-Performance Gaming Laptop",
        category: "Laptops",
        price: "1299.00",
        oldPrice: "1499.00",
        imageUrl: "https://unsplash.com/photos/a-person-playing-a-video-game-on-a-laptop-auf3GwpVaOM",
        amazonLink: "#",
        rating: 4.9,
        reviewCount: 400,
        onPromotion: true,
        shortDescription: "Top-tier gaming laptop with powerful specs for an immersive experience."
    },
    {
        id: "prod009",
        slug: "mechanical-gaming-keyboard",
        name: "Mechanical Gaming Keyboard",
        category: "Computer Accessories",
        price: "99.99",
        imageUrl: "https://unsplash.com/photos/a-computer-keyboard-sitting-on-top-of-a-blue-surface-t5uM-M-WCN0",
        amazonLink: "#",
        rating: 4.5,
        reviewCount: 160,
        onPromotion: false,
        shortDescription: "RGB mechanical keyboard with responsive keys for gaming and typing."
    },
    {
        id: "prod010",
        slug: "compact-espresso-maker",
        name: "Compact Espresso Maker",
        category: "Kitchen Appliances",
        price: "79.99",
        imageUrl: "https://www.pexels.com/photo/black-coffeemaker-with-red-ceramic-teacup-362216/",
        amazonLink: "#",
        rating: 4.3,
        reviewCount: 120,
        onPromotion: true,
        shortDescription: "Space-saving and efficient espresso maker for quick coffee fixes."
    }
]

export default products;
